# Dynamic programming and edit distance
* Just to remind you: we have two implementations of the edit-distance function: (1) recursive, (2) dynamic programming matrix

In [4]:
def EditDistance(s, t):
    if s == "":
        return len(t)
    if t == "":
        return len(s)
    if s[-1] == t[-1]:
        cost = 0
    else:
        cost = 1
       
    res = min([EditDistance(s, t[:-1])+1, # Delete
               EditDistance(s[:-1], t)+1, # Insert
               EditDistance(s[:-1], t[:-1]) + cost]) # Replace
    return res

In [5]:
import numpy as np

def EditDistanceM(s, t):  
    size_x = len(s) + 1
    size_y = len(t) + 1
    matrix = np.zeros ((size_x, size_y))
    

    for x in range(size_x):
        matrix[x, 0] = x
    for y in range(size_y):
        matrix[0, y] = y

        
    for x in range(1, size_x):
        for y in range(1, size_y):
            if s[x-1] == t[y-1]:
                matrix[x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix[x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    
    # Comment out the print message!! print (matrix)
    # Return the tuple (distance, matrix) instead of returning just the distance.
    # Remember: we can return multiple values from fucntions using tuples!
    return (matrix[size_x - 1, size_y - 1], matrix)

In [6]:
results = EditDistanceM("TUC", "ACTUA")
print("Distance= ", results[0])
print("Matrix=\n", results[1])

Distance=  3.0
Matrix=
 [[0. 1. 2. 3. 4. 5.]
 [1. 1. 2. 2. 3. 4.]
 [2. 2. 2. 3. 2. 3.]
 [3. 3. 2. 3. 3. 3.]]


# From costs to operations in EditDistanceM
* What are the numbers in the cells of a dynamic programming matrix?
* Show the type of operations (insert, delete, replace) instead of showing the cost.

How?
* Suppose you are at cell c, at position [x,y] (x row, y column), and the cell corresponds to similar bases.
 * Get the content of cell above c (position [x-1,y]) plus 1, the content of cell on the upper left of c (position [x-1, y-1]), 
and the content of cell on the left of c (position [x, y-1]) + 1
 * ...and find the min: matrix[x,y] = min(values)

* Suppose you are at cell c, at position [x,y] (x row, y column), and the cell corresponds to different bases.
 * Get the content of cell above c (position [x-1,y]) plus 1, the content of cell on the upper left of c (position [x-1, y-1]) <b>plus one</b>, 
and the content of cell on the left of c (position [x, y-1]) + 1
 * ...and find the min: matrix[x,y] = min(values)

* Consider a values list: values.index(4): returns the position of 4 (counting from 0!!!) in values list. E.g., if values is [3,2,4,1,0], then values.index(4) returns 2.

* Consider a values list with 3 elements: the 1st (position 0) corresponds to a deletion operation, the 2nd (position 1) corresponds to a replace operation,
and the 3rd (position 2) corresponds to an insert operation. 
* matrix_tr[x,y] = values.index(min(values)): we assign to the matrix_tr cell 0 or 1 or 2, depending on the result of min(values)! 






In [5]:
import numpy as np

def EditDistanceM_tr(s, t):  
    size_x = len(s) + 1
    size_y = len(t) + 1
    matrix = np.zeros ((size_x, size_y))
    matrix_tr = np.zeros ((size_x, size_y)) # <======= CHANGE (Init traceback matrix)
    
    for x in range(size_x):
        matrix[x, 0] = x
        matrix_tr[x,0] = 0 # all cells of the first column correspond to deletions (0) of the first string to get empty string
    for y in range(size_y):
        matrix[0, y] = y
        matrix_tr[0,y] = 2 # all cells of first line correspond to insertions (2) in an empty string

    matrix_tr[0,0] = 0 # reset the "root" cell
    
    for x in range(1, size_x):
        for y in range(1, size_y):
            if s[x-1] == t[y-1]:
                values = [matrix[x-1, y]+1, matrix[x-1, y-1], matrix[x, y-1]+1]
                matrix[x,y] = min(values)
                matrix_tr[x,y] = values.index(min(values)) # <============= CHANGE (0=del, 1=match, 2=ins)
            else:
                values = [matrix[x-1,y]+1, matrix[x-1,y-1]+1, matrix[x,y-1]+1]
                matrix[x,y] = min(values)
                matrix_tr[x,y] = values.index(min(values)) # <============= CHANGE (0=del, 1=mismatch, 2=ins)
    return (matrix[size_x - 1, size_y - 1], matrix, matrix_tr)

In [6]:
results = EditDistanceM_tr("TUC","ACTUA")
print("Distance= ", results[0])
print("Matrix=\n", results[1])
print("Matrix_tr=\n", results[2])

Distance=  3.0
Matrix=
 [[0. 1. 2. 3. 4. 5.]
 [1. 1. 2. 2. 3. 4.]
 [2. 2. 2. 3. 2. 3.]
 [3. 3. 2. 3. 3. 3.]]
Matrix_tr=
 [[0. 2. 2. 2. 2. 2.]
 [0. 1. 1. 1. 2. 2.]
 [0. 0. 1. 0. 1. 2.]
 [0. 0. 1. 1. 0. 1.]]
